set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(DICTPEN_TOOLCHAIN_ROOT
    "/opt/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu"
    CACHE PATH "ARM GNU toolchain root")

set(DICTPEN_TOOLCHAIN_PREFIX
    "${DICTPEN_TOOLCHAIN_ROOT}/bin/aarch64-none-linux-gnu-")

set(CMAKE_C_COMPILER "${DICTPEN_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${DICTPEN_TOOLCHAIN_PREFIX}g++")
set(CMAKE_AR "${DICTPEN_TOOLCHAIN_PREFIX}ar")
set(CMAKE_RANLIB "${DICTPEN_TOOLCHAIN_PREFIX}ranlib")
set(CMAKE_STRIP "${DICTPEN_TOOLCHAIN_PREFIX}strip")

set(CMAKE_SYSROOT
    "${DICTPEN_TOOLCHAIN_ROOT}/aarch64-none-linux-gnu/libc")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
